### ISSUE TITLE
Make pywatch with no params show usage.

### ISSUE THREAD

**Issue by zellyn** [cmheisel/pywatch#1]
<pre>
curdie:~ zhunter$ pywatch
Traceback (most recent call last):
  File "/usr/bin/pywatch", line 5, in ?
    pkg_resources.run_script('pywatch==0.3', 'pywatch')
  File "/opt/local/lib/python2.4/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/local/lib/python2.4/site-packages/pkg_resources.py", line 1166, in run_script
    execfile(script_filename, namespace, namespace)
  File "/opt/local/lib/python2.4/site-packages/pywatch-0.3-py2.4.egg/EGG-INFO/scripts/pywatch", line 3, in ?
    pywatch.main()
  File "/opt/local/lib/python2.4/site-packages/pywatch-0.3-py2.4.egg/pywatch/__init__.py", line 25, in main
    cmds = [args[0], ]
IndexError: list index out of range
</pre>

**Comment by cmheisel** [comment]
Zellyn, this should is fixed in the new 0.3.1 release. Give it a go and let me know what you think.
